# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: true

# Social
social:
  twitter: aozora0000
  twitter_site: '@aozora0000'
  twitter_card: summary
  
# Miscellaneous
favicon: /favicon.ico
